##TRACKING CONFIG
# ------------------- General Options -------------------------
description                  : AB3DMOT
seed                         : 0
# --------------- main.py
save_root                    : ./data/track_exp/KITTI/exp
dataset                      : KITTI      # KITTI
split                        : val        # val, test
det_name                     : diff3  # name of the detector [pointrcnn, pvrcnn]/ gt
cat_list                     : ['car'] #['Car', 'Pedestrian', 'Cyclist']
#--------------- SEQ
seq_eval                     : [1,2,5,7,8,9,11,18,19,20] #sequence to track, [] means by default
# --------------- model.py
ego_com                      : True      # turn on only slightly reduce speed but increase a lot for performance
#---------------- addition
label_format                 : Kitti      # Kitti, Waymo, nuscenes, AB3DMOT
label_coord                  : camera       # lidar or camera
output_kf_cls                : True ## if true output kf car as KF_Car class
output_mode                  : 'kf' ## output by interpolate or kf predict
kf_initial_speed             : 30 #km/h
conf_thres                   : 0.0 
# ------------------NDT
NDT_flag                     : True
pcd_db_root                  : "./data/KITTI/dense_db/demos/demo_gtdets_car/"
NDT_cfg                      : {'voxel_size': 0.5, 'overlap': True, 'min_pts_voxel': 5, 'noise': 0.05}
NDT_cache_root               : "./data/KITTI/NDT_pkl/gtdet/"
NDT_cache_name               : "demo_gtdets_car_cache" #path for load/write
NDT_thres                    : {'car': {'NDT_score': -15000,'max_dist': 6.0,'max_angle': 20},
                                'cyclist': {'NDT_score': -15000,'max_dist': 4.5,'max_angle': 20}} 
#---------------AB3DMOT base
base_param                   : {'car':{'algm': 'hungar', 'metric': 'giou_3d', 'thres': 0.2, 'min_hits': 1, 'max_age': 60},
                                'cyclist':{'algm': 'hungar', 'metric': 'dist_3d', 'thres': 2.0, 'min_hits': 1, 'max_age': 60}}          
# --------------- DA stage2 threshold
two_stage                   : True     
stage2_param                : {'car':{'algm': 'hungar', 'metric': 'dist_3d', 'thres': 3.0},
                                'cyclist':{'algm': 'hungar', 'metric': 'dist_3d', 'thres': 3.0}}    