##EVALUATION CONFIG
# ------------------- Dataset Name -------------------------
description                  : KITTI
# ------------------- Path Options -------------------------
gt_path                      : "./label/" 
calib_path                   : "../../data/KITTI/tracking/training/calib/"
trk_path                     : "../../data/track_exp/KITTI/exp/label"
out_path                     : "../../data/track_exp/KITTI/exp/" 
exp_name                     : eval
# ------------------- Eval Options -------------------------
iou                          : 3D
threshold                    : [0.25,0.5]
class_name                   : ['car']
gt_format                    : KITTI
trk_format                   : KITTI
num_hypo                     : 1
max_occlusion                : 4 
max_truncation               : 2 #0,1,2
eval_seq                     : [1,6,8,10,12,13,14,15,16,18,19] #[1,2,5,7,8,9,11,18,19,20] 
fov_filter                   : False
